# Generated by Django 5.2.7 on 2025-11-04 03:56

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Criado em"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_images/",
                validators=[posts.models.validate_image_file],
                verbose_name="Imagem",
            ),
        ),
    ]
